/**
 * `grenz protect [--tool github] [--strict] [--home <dir>]` — outcome-first
 * onboarding in one verb. Scaffolds a home if absent, moves the upstream
 * credential into the vault (read from stdin or <TYPE>_TOKEN — never printed or
 * logged), writes a safe-defaults policy the user authors nothing of, and prints
 * a falsifiable outcome.
 */
import { mkdir, chmod } from "node:fs/promises";
import { grenzPaths } from "../config/paths.ts";
import { AgeFileCredentialStore } from "../vault/age-file.ts";
import { ensureAdminToken } from "../admin/token.ts";
import { generateToken, hashToken } from "../util/token.ts";
import { buildSafeDefaults, renderPolicyYaml, type Preference } from "../policy/safe-defaults.ts";
import { renderProtectOutcome } from "../wrap/protect-outcome.ts";
import { flagBool, flagString, homeFlag, type ParsedArgs } from "./args.ts";

interface Preset {
  readonly type: string;
  readonly baseUrl: string;
  readonly credential: string;
  readonly header: string;
  readonly scheme: string;
  readonly env: string;
}

const PRESETS: Readonly<Record<string, Preset>> = {
  github: {
    type: "github",
    baseUrl: "https://api.github.com",
    credential: "github_token",
    header: "Authorization",
    scheme: "Bearer",
    env: "GITHUB_TOKEN",
  },
};

const DEFAULT_AGENT = "claude-code";
const LISTEN = { host: "127.0.0.1", port: 8787 } as const;

function grenzYaml(agentId: string, tokenHash: string, name: string, preset: Preset): string {
  return `# grenz.yaml — non-secret runtime config (generated by \`grenz protect\`).
# Credential VALUES live only in the age vault; this file holds routing + the
# agent's token hash. Safe to commit.

listen:
  host: ${LISTEN.host}
  port: ${LISTEN.port}

upstreams:
  ${name}:
    type: ${preset.type}
    base_url: ${preset.baseUrl}
    credential: ${preset.credential}
    inject:
      header: ${preset.header}
      scheme: ${preset.scheme}

agents:
  - id: ${agentId}
    token_hash: ${tokenHash}
`;
}

/** stdin (piped) first, then the env var. The raw value is never logged. */
async function readSecret(envVar: string): Promise<string | null> {
  if (!process.stdin.isTTY) {
    try {
      const t = (await Bun.stdin.text()).trim();
      if (t) return t;
    } catch {
      /* no stdin — fall through to env */
    }
  }
  const e = process.env[envVar];
  return e && e.trim() ? e.trim() : null;
}

export async function runProtect(args: ParsedArgs): Promise<number> {
  const tool = flagString(args, "tool") ?? "github";
  const preset = PRESETS[tool];
  if (!preset) {
    process.stderr.write(`grenz: protect v1 supports --tool github (got "${tool}").\n`);
    return 1;
  }
  const preference: Preference = flagBool(args, "strict") ? "strict" : "normal";
  const paths = grenzPaths(homeFlag(args));

  if ((await Bun.file(paths.config).exists()) && !flagBool(args, "force")) {
    process.stdout.write(
      `  ${paths.home} is already set up. Point your agent at ` +
        `http://${LISTEN.host}:${LISTEN.port}/u/${tool}, or run \`grenz status\`.\n` +
        `  Re-run with --force to regenerate the config + safe-defaults policy.\n`,
    );
    return 0;
  }

  const secret = await readSecret(preset.env);
  if (!secret) {
    process.stderr.write(
      `grenz: no ${tool} credential provided.\n` +
        `  Pipe it in — it is never printed or logged:\n` +
        `      printf %s "$${preset.env}" | grenz protect${tool === "github" ? "" : ` --tool ${tool}`}\n`,
    );
    return 1;
  }

  process.stdout.write("\n" + (await applyProtect({ paths, tool, preset, preference, secret })) + "\n");
  return 0;
}

export interface ProtectInput {
  readonly paths: ReturnType<typeof grenzPaths>;
  readonly tool: string;
  readonly preset: Preset;
  readonly preference: Preference;
  readonly secret: string;
  readonly agent?: string;
}

/**
 * The protect core: scaffold what's absent, move the secret into the vault, and
 * write the safe-defaults policy. Returns the outcome text. Takes the secret as
 * a parameter (no stdin) so it is unit-testable; the raw value is written ONLY
 * to the vault — never to stdout/stderr or any log line.
 */
export async function applyProtect(input: ProtectInput): Promise<string> {
  const { paths, tool, preset, preference, secret } = input;
  const agent = input.agent ?? DEFAULT_AGENT;

  await mkdir(paths.home, { recursive: true });
  if (!(await Bun.file(paths.identity).exists())) {
    const { identity } = await AgeFileCredentialStore.generateIdentity();
    await Bun.write(paths.identity, `${identity}\n`);
    await chmod(paths.identity, 0o600);
  }
  const vault = new AgeFileCredentialStore({ identityPath: paths.identity, vaultPath: paths.vault });
  if (!(await Bun.file(paths.vault).exists())) await vault.createEmpty();
  await ensureAdminToken(paths.adminToken);

  const grenzToken = generateToken();
  const tokenHash = await hashToken(grenzToken);
  await Bun.write(paths.config, grenzYaml(agent, tokenHash, tool, preset));
  await vault.set(preset.credential, secret);

  const grants = buildSafeDefaults([{ name: tool, type: preset.type }], preference);
  await Bun.write(paths.policy, renderPolicyYaml(grants, { agent, onBehalfOf: "you@example.com", preference }));

  return renderProtectOutcome({
    upstreamName: tool,
    envVar: preset.env,
    listen: LISTEN,
    grant: grants[0]!,
    grenzToken,
    policyPath: paths.policy,
    preference,
  });
}

export { PRESETS };
