/**
 * Safe-defaults generator — turns a user's *preference* ("normal" / "strict")
 * and their set of upstreams into a policy, using the per-adapter action
 * classification. The user authors nothing.
 *
 * The one rule that threads too-tight vs too-loose: **never generate a `deny`.**
 * Irreversible / unclassified actions resolve to `require_approval` (a 5-minute
 * human interrupt), so a default can't break the agent mid-task — it can only
 * ask. Deny-by-default still applies at the engine floor for anything unlisted.
 *
 * Pure and synchronous.
 */

import { classifyAction, vocabulary, TAIL_TYPES } from "../adapters/classify.ts";

export type Preference = "normal" | "strict";

export interface UpstreamRef {
  readonly name: string;
  readonly type: string;
}

export interface SafeGrant {
  readonly tool: string;
  readonly allow: string[];
  readonly require_approval: string[];
}

/** Catch-all for unknown MCP-transport tools (`call:<tool>`). */
const TAIL = "call:*";

export function buildSafeDefaults(
  upstreams: readonly UpstreamRef[],
  preference: Preference = "normal",
): SafeGrant[] {
  return upstreams.map((u) => {
    const allow: string[] = [];
    const approval: string[] = [];

    if (u.type === "mcp") {
      // Generic MCP tools carry no risk classification. The honest default is
      // permissive-and-observed, stated plainly in the policy — tighten later
      // with shrinkwrap. (Tier-1 token isolation holds regardless.)
      return { tool: u.name, allow: [TAIL], require_approval: [] };
    }

    for (const action of vocabulary(u.type)) {
      const cls = classifyAction(u.type, action);
      const needsApproval =
        cls === "destructive" || cls === "exfil" || (preference === "strict" && cls === "sensitive");
      (needsApproval ? approval : allow).push(action);
    }

    // Unknown tools on MCP-transport adapters ask, never deny.
    if (TAIL_TYPES.has(u.type)) approval.push(TAIL);

    return { tool: u.name, allow: allow.sort(), require_approval: approval.sort() };
  });
}

export interface RenderOpts {
  readonly agent: string;
  readonly onBehalfOf: string;
  readonly preference: Preference;
}

/** Serialize safe-defaults to a readable, user-owned policy.yaml. */
export function renderPolicyYaml(grants: readonly SafeGrant[], opts: RenderOpts): string {
  const lines: string[] = [
    `# policy.yaml — generated by \`grenz protect\` (preference: ${opts.preference}).`,
    `#`,
    `# This file is yours: read it, edit it, commit it. Deny-by-default — anything`,
    `# not listed is denied. Irreversible actions ask for your approval; they are`,
    `# never silently allowed. Run \`grenz shrinkwrap\` to tighten it to what your`,
    `# agent actually does.`,
    `agent: ${opts.agent}`,
    `on_behalf_of: ${opts.onBehalfOf}`,
    `grants:`,
  ];
  for (const g of grants) {
    lines.push(`  - tool: ${g.tool}`);
    if (g.allow.length > 0) {
      lines.push(`    allow:`);
      for (const a of g.allow) lines.push(`      - ${quote(a)}`);
    }
    if (g.require_approval.length > 0) {
      lines.push(`    require_approval:`);
      for (const a of g.require_approval) lines.push(`      - ${quote(a)}`);
    }
  }
  // Kill-switch (opt-in, left commented so a fresh policy never breaks an honest
  // agent). A tripwire revokes on the mere ATTEMPT of an action — and by default
  // CASCADES, killing a raided agent's whole delegation tree at once. Deletes are
  // already denied above, so an attempt is itself the signal. Uncomment to arm.
  lines.push(
    ``,
    `# Kill-switch (opt-in). A tripwire revokes on the mere ATTEMPT of an action,`,
    `# and by default cascades — one raided sub-agent kills the whole tree. Use`,
    `# \`on_trip: leaf\` to revoke only the sub-token that tripped. Stronger still:`,
    `# plant a decoy with \`grenz decoy\` — nobody legitimate ever touches it.`,
    `# tripwires:`,
    `#   - action: "repo:delete"`,
    `#     note: "destructive — never allowed"`,
  );
  return lines.join("\n") + "\n";
}

// A `*` at the end (e.g. `call:*`) is a YAML alias sigil unless quoted.
function quote(action: string): string {
  return /[*:]/.test(action) ? `"${action}"` : action;
}
